import Navbar from '@/components/Navbar/Navbar'
import './globals.css'
import Footer from '@/components/Footer/Footer'
import Subscribe from '@/components/Subscribe/Subscribe'


export const metadata = {
  title: 'ShoppingMarket',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Subscribe />
        <Navbar />
        {children}
        <Footer />
        </body>
    </html>
  )
}
